EXCLUDE_DIRS = frozenset({
    '.git', '.svn', '.hg',
    'node_modules', '__pycache__', '.venv', 'venv', 'env', '.env',
    'dist', 'build', 'out', 'target', '.next', '.nuxt', '.output',
    'vendor', 'Pods', '.gradle', '.idea', '.vscode',
    'coverage', '.cache', '.tmp', '.temp', '.tox', '.mypy_cache', '.pytest_cache',
    '.code-compass',
})

CODE_EXTENSIONS = {
    '.py': 'python',
    '.ts': 'typescript',
    '.tsx': 'typescript',
    '.js': 'javascript',
    '.jsx': 'javascript',
    '.java': 'java',
    '.go': 'go',
}

FILE_LIMIT = 200

OVERVIEW_DIR_DEPTH = 2

SKIP_METHOD_NAMES = frozenset({
    'get', 'set', 'pop', 'update', 'clear', 'copy', 'items', 'keys', 'values',
    'append', 'extend', 'insert', 'remove', 'discard', 'add',
    'sort', 'reverse', 'count', 'index',
    'split', 'join', 'strip', 'lstrip', 'rstrip', 'replace',
    'startswith', 'endswith', 'find', 'rfind', 'index', 'rindex',
    'upper', 'lower', 'capitalize', 'title', 'swapcase',
    'encode', 'decode', 'format', 'format_map',
    'isdigit', 'isalpha', 'isalnum', 'isspace', 'isupper', 'islower',
    'strip', 'lstrip', 'rstrip',
    'read', 'readline', 'readlines', 'write', 'writelines', 'close', 'flush',
    'seek', 'tell',
    'group', 'start', 'end', 'span', 'groups',
    'finditer', 'search', 'match', 'sub', 'subn', 'escape', 'fullmatch',
    'hexdigest', 'hex',
    'isoformat', 'strftime', 'strptime',
    'now', 'today', 'utcnow',
    'iter', 'next',
    'open', 'close',
    'name', 'parent', 'stem', 'suffix', 'exists', 'is_file', 'is_dir',
    'mkdir', 'rmdir', 'unlink', 'rename', 'replace',
    'resolve', 'absolute', 'relative_to',
    'walk', 'stat',
    'json', 'dumps', 'loads',
    'dump', 'load',
    'to_dict', 'from_dict', 'to_json', 'from_json',
    'astype', 'dtype', 'shape', 'reshape', 'transpose', 'flatten',
    'tolist', 'array',
    'bind', 'execute', 'fetchall', 'fetchone', 'commit', 'rollback',
    'cursor', 'close',
    'query', 'filter', 'all', 'first', 'last',
    'text', 'clause',
    'send', 'recv', 'connect', 'disconnect', 'listen', 'accept',
    'put', 'post', 'delete', 'patch', 'head', 'options',
    'abort', 'redirect',
    'url_for', 'render_template',
    'main', 'run',
})

DIR_ROLE_HINTS = {
    'src': '主要源码',
    'lib': '库代码',
    'app': '应用主代码',
    'api': 'API 接口定义',
    'routes': '路由定义',
    'controllers': '请求处理/控制器',
    'models': '数据模型',
    'views': '视图/页面渲染',
    'services': '业务逻辑/服务层',
    'middleware': '中间件',
    'utils': '工具函数',
    'helpers': '工具函数',
    'components': 'UI 组件',
    'pages': '页面',
    'config': '配置文件',
    'conf': '配置文件',
    'tests': '测试文件',
    'test': '测试文件',
    'spec': '测试文件',
    '__tests__': '测试文件',
    'scripts': '脚本',
    'docs': '文档',
    'types': '类型定义',
    'interfaces': '类型定义',
    'constants': '常量定义',
    'handlers': '事件/请求处理器',
    'store': '状态管理',
    'stores': '状态管理',
    'hooks': '自定义 Hooks',
    'styles': '样式文件',
    'assets': '静态资源',
    'static': '静态资源',
    'public': '静态资源',
    'migrations': '数据库迁移',
    'seeders': '数据库种子',
    'entities': '实体类',
    'repositories': '数据访问层',
    'dto': '数据传输对象',
    'validators': '数据校验',
    'exceptions': '异常定义',
    'errors': '异常定义',
    'listeners': '事件监听器',
    'providers': '服务提供者',
    'commands': '命令定义',
    'queries': '查询定义',
    'workers': '后台任务',
    'channels': '通道/消息处理',
    'policies': '权限策略',
    'rules': '业务规则',
    'events': '事件定义',
    'notifications': '通知',
    'jobs': '异步任务',
    'mail': '邮件',
    'exports': '导出',
    'imports': '导入',
    'resources': '资源转换',
    'presenters': '展示层',
    'serializers': '序列化',
    'forms': '表单',
    'tasks': '任务定义',
    'decorators': '装饰器',
    'filters': '过滤器',
    'middlewares': '中间件',
    'guards': '守卫',
    'interceptors': '拦截器',
    'pipes': '管道',
    'adapters': '适配器',
    'factories': '工厂',
    'strategies': '策略',
    'observers': '观察者',
    'subscribers': '订阅者',
    'publishers': '发布者',
    'consumers': '消费者',
    'producers': '生产者',
}
